name: CI pipeline

on: push

jobs: 
    project-testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
                pip install dvc
            
            - name: Run DVC pipeline
              env:
                DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
              run: |
                dvc repro

            - name: Run Model tests
              env:
                DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
              run: |
                python -m unittest tests/model_test.py
            
            - name: Promote model to production
              if: success()
              env:
                DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
              run: python scripts/production.py
            
            # Log in to DockerHub
            - name: Log in to Dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            # Build the Docker image
            - name: Build Docker Image
              if: ${{success()}}
              run: |
                docker build -t sfgrahman/water-potability-predictor:latest .
            
            # Push the Docker image only if the build step was successful
            - name: Push Docker Image
              if: ${{ success()}}
              run: |
                docker push sfgrahman/water-potability-predictor:latest .

